//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfStickers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfStickers.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13287;3DMAX (голографическая) | Катовице 2014
        ///130504;3DMAX (металлическая) | Катовице 2014
        ///63;3DMAX | Катовице 2014
        ///13317;Clan-Mystik (голографическая) | Катовице 2014
        ///189648;Clan-Mystik (металлическая) | Катовице 2014
        ///8930;Clan-Mystik | Катовице 2014
        ///13484;compLexity Gaming (голографическая) | Катовице 2014
        ///13307;compLexity Gaming (металлическая) | Катовице 2014
        ///6084;compLexity Gaming | Катовице 2014
        ///8080;Fnatic (голографическая) | Катовице 2014
        ///28181;Fnatic (металлическая) | Катовице 2014
        ///5497; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stikers {
            get {
                return ResourceManager.GetString("Stikers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13287
        ///130504
        ///13317
        ///189648
        ///8930
        ///13484
        ///13307
        ///6084
        ///8080
        ///28181
        ///5497
        ///8964
        ///28134
        ///6469
        ///82591
        ///1010038
        ///12532
        ///11224
        ///28172
        ///5820
        ///13584
        ///395564
        ///6082
        ///13461
        ///189649
        ///8938
        ///11010
        ///13084
        ///8081
        ///13467
        ///28180
        ///6040
        ///28102
        ///28136
        ///1178
        ///13468
        ///168263
        ///1622
        ///11223
        ///366411
        ///7888
        ///13105
        ///13083
        ///5241
        ///13330
        ///130506
        ///8985
        ///13308
        ///28131
        ///13085
        ///7734
        ///.
        /// </summary>
        internal static string Stikers2 {
            get {
                return ResourceManager.GetString("Stikers2", resourceCulture);
            }
        }
    }
}
